http:
  routers:
    amas-api:
      rule: "Host(`api.amaslohaceposible.cloud`)"
      entryPoints:
        - websecure
      tls:
        certResolver: le
      service: amas-api

  services:
    amas-api:
      loadBalancer:
        servers:
          - url: "http://amas-api:8080"
