services:
  amas-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amas-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - amas_net
      - traefik_proxy
    restart: unless-stopped

networks:
  amas_net:
    external: true
  traefik_proxy:
    external: true
